version: '3.3'

services:
  database:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: books
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
  php:
    container_name: php
    build:
      context: .
    volumes:
      - ./:/app:rw
    depends_on:
      - database